# Generated by Django 4.1.3 on 2023-04-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
